"""
Django settings for ecommerce project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

APPEND_SLASH = True

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-59l4ijsn*10pfp+h0e*x=+icgj4kvxskqf-*fr^ki6vdh)hzj8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost', 
    '127.0.0.1',
    '.preview.app.github.dev',
    '.github.dev',
]
CSRF_TRUSTED_ORIGINS = [
    'https://localhost:8000',
    'https://*.preview.app.github.dev', # This wildcard allows all subdomains
    'https://*github.dev', # For standard github.dev URLs
]

# Application definition

INSTALLED_APPS = [
    #'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'base',
    'products',
    'members',
    'admin',
    'phonenumber_field',
    'rest_framework',
    'corsheaders',
    'django_vite',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', #near the top
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecommerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecommerce.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#Static (CSS)

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
    BASE_DIR / "frontend/dist",    # backup caso precise
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

IS_CODESPACES = "CODESPACE_NAME" in os.environ

DJANGO_VITE = {
    "default": {
        "dev_mode": True,   # ou DEBUG
        "dev_server_protocol": "https",
        "dev_server_host": (
            f"{os.getenv('CODESPACE_NAME')}-5173.{os.getenv('GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN')}"
            if IS_CODESPACES else "localhost"
        ),
        "dev_server_port": 5173,
    }
}

#Media Servers

MEDIA_URL = '/media/' #URL that handles the media served from MEDIA_ROOT.
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
#MEDIA_ROOT = BASE_DIR / 'media' # Absolute filesystem path to the directory that will hold user-uploaded files.

AUTH_USER_MODEL = 'base.CustomUser'

# Default region for parsing (e.g., 'US' for USA)
PHONENUMBER_DEFAULT_REGION = 'US'

# Default display format (options: 'E164', 'INTERNATIONAL', 'NATIONAL', 'RFC3966')
PHONENUMBER_DEFAULT_FORMAT = 'INTERNATIONAL'

# Database storage format (usually matches display)
PHONENUMBER_DB_FORMAT = 'INTERNATIONAL'

