# Generated by Django 5.2 on 2025-12-02 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_date_of_birth_customuser_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='dob',
            new_name='date_of_birth',
        ),
    ]
